# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: My Information Just Under Glass
email: devopsbob@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Computer related information and blogging content.
company: Kranson Enterprises
author: Bob Kranson
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  devopsbob
linkedin_username: bobkranson
logo: /assets/logo-mijug-watermark-98x100.svg # path to your logo image
favicon: /assets/favicon.ico # path to your favicon image

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - docs
  - scripts
  - README.md
  - LICENSE
  - frontmatter.json

webrick:
  headers:
    # Add Content-Security-Policy header to enhance security
    # This example allows scripts, styles, images, and connections from the same origin
    # Adjust the policy as needed for your site requirements
    Content-Security-Policy: default-src 'self'; script-src 'self' 'strict-dynamic' 'unsafe-inline' https://www.freecounterstat.com https://counter1.optistats.ovh https://pagead2.googlesyndication.com; connect-src 'self' https://pagead2.googlesyndication.com; img-src 'self'; style-src 'self' 'unsafe-inline'; font-src 'self'; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'; upgrade-insecure-requests; block-all-mixed-content
  # Note: The above policy is a basic example. You may need to adjust it based
    Access-Control-Allow-Origin: '*' # Allow all origins for CORS
  # This is useful for development purposes, but consider restricting
  # this in production environments but will impact the ability to load resources from other domains.
  # such as Google AdSense or other third-party services.
    Access-Control-Allow-Credentials: true # Allow credentials to be included in CORS requests
  # This allows cookies, authorization headers, or TLS client certificates to be included in CORS
  # requests, which is often necessary for authenticated requests.
    Access-Control-Allow-Headers: 'Content-Type, Authorization, X-Requested-With' # Allow specific headers
  # This allows the specified headers to be included in CORS requests.
  # Adjust the headers as needed for your application.
    Access-Control-Allow-Methods: 'GET, POST, OPTIONS' # Allow specific methods
  # This allows GET, POST, and OPTIONS methods for CORS requests.
    Permissions-Policy: accelerometer=(), attribution-reporting=(), autoplay=(), bluetooth=(), browsing-topics=(), camera=(), captured-surface-control=(), ch-device-memory=(), ch-downlink=(), ch-dpr=(), ch-ect=(), ch-prefers-color-scheme=(), ch-prefers-reduced-motion=(), ch-prefers-reduced-transparency=(), ch-rtt=(), ch-save-data=(), ch-ua=(), ch-ua-arch=(), ch-ua-bitness=(), ch-ua-form-factors=(), ch-ua-full-version=(), ch-ua-full-version-list=(), ch-ua-mobile=(), ch-ua-model=(), ch-ua-platform=(), ch-ua-platform-version=(), ch-ua-wow64=(), ch-viewport-height=(), ch-viewport-width=(), ch-width=(), clipboard-read=(), clipboard-write=(), compute-pressure=(), cross-origin-isolated=(), deferred-fetch=(), deferred-fetch-minimal=(), display-capture=(), encrypted-media=(), fullscreen=(), gamepad=(), geolocation=(), gyroscope=(), hid=(), identity-credentials-get=(), idle-detection=(), interest-cohort=(), join-ad-interest-group=(), keyboard-map=(), language-detector=(), local-fonts=(), magnetometer=(), microphone=(), midi=(), otp-credentials=(), payment=(), picture-in-picture=(), private-aggregation=(), private-state-token-issuance=(), private-state-token-redemption=(), publickey-credentials-create=(), publickey-credentials-get=(), rewriter=(), run-ad-auction=(), screen-wake-lock=(), serial=(), shared-storage=(), shared-storage-select-url=(), storage-access=(), summarizer=(), sync-xhr=(), translator=(), unload=(), usb=(), web-share=(), window-management=(), writer=(), xr-spatial-tracking=()
